# Data analysis with Python

#### This is the process of inspecting,cleansing,transforming and modelling data with the goal of discovering new and useful insights, informing conclusions and supporting decision making.

#### Why Python ?
- Open Sorce
- Free
- Rich set of Libraries
- Easy to learn(English-like syntax)

#### Other tools used
* Julia
* R
* Spreadsheets
* Tableau

In [3]:
# Let's import the pandas library 
# 
import pandas as pd

In [2]:
# Converting dictionaries to dataframes
data = [{'name': 'vikash', 'age': 27}, {'name': 'Satyam', 'age': 14}]
df = pd.DataFrame.from_dict(data, orient='columns')
df


name  age
0  vikash   27
1  Satyam   14

In [2]:
# Creating Datafame from random values

from random import randint

# Declare the columns that we will need 
columns = ['a', 'b', 'c']

df = pd.DataFrame(columns=columns)


# The .loc method works in the same way slicing works in python list,loc[] to insert the random number in either of the columns 
# thus we are simply updating the null elements with values.
for i in range(7):
    for c in columns:
      df.loc[i,c] = randint(-1,1)
  
# and printing out the dataframe
df

a   b   c
0  -1   1   1
1   1   1  -1
2   0   1  -1
3  -1  -1   1
4   1  -1  -1
5   0  -1   1
6   0  -1   0

In [ ]:
#reading data using url
df_url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
df = pd.read_csv(df_url)
df.head(10)

Country  Region
0                   Algeria  AFRICA
1                    Angola  AFRICA
2                     Benin  AFRICA
3                  Botswana  AFRICA
4                   Burkina  AFRICA
5                   Burundi  AFRICA
6                  Cameroon  AFRICA
7                Cape Verde  AFRICA
8  Central African Republic  AFRICA
9                      Chad  AFRICA

In [ ]:
# Changing Dataframe column names 
# 
student_list = [['Derrick', 1, 'a'],['Austin', 2, 'a'],['Dorris', 3, 'a']]

students = pd.DataFrame(student_list, columns = ['name','class','grade'])
students

students.columns.values[1:] = ['student_' + val for val in students.columns.values[1:]]
students.columns.values
students


name  student_class student_grade
0  Derrick              1             a
1   Austin              2             a
2   Dorris              3             a

In [ ]:
# A simpler way of changing Dataframe column names 
#
student_list = [['Derrick', 1, 'a'],['Austin', 2, 'a'],['Dorris', 3, 'a']]
students = pd.DataFrame(student_list, columns = ['name','class','grade'])
students

# Uncomment the following line
students.columns = ['names', 'Grade', 'Score']
students

names  Grade Score
0  Derrick      1     a
1   Austin      2     a
2   Dorris      3     a

In [ ]:
# Dropping columns
# Axis 0 - rows 1 - columns
# Inplace = true - makes changes permanent
df.drop('Region', axis=1, inplace=True)
df

Country
0      Algeria
1       Angola
2        Benin
3     Botswana
4      Burkina
..         ...
189   Paraguay
190       Peru
191   Suriname
192    Uruguay
193  Venezuela

[194 rows x 1 columns]

In [ ]:
df1 = df.head(10)
df1

Country
0                   Algeria
1                    Angola
2                     Benin
3                  Botswana
4                   Burkina
5                   Burundi
6                  Cameroon
7                Cape Verde
8  Central African Republic
9                      Chad

In [ ]:
for index, row in df1.iterrows():
  print(row['Country'], row['Region'])

In [ ]:
for row in df1.itertuples():
  print(row)

In [ ]:
# A simpler way of changing Dataframe column names 
#
student_list = [['Derrick', 1],['Austin', 2],['Dorris', 3]]
students = pd.DataFrame(student_list, columns = ['name','class',])


students_list2 = [['Derrick', 'A'],['Austin',"B" ],['Dorris',"A"]]
students1 = pd.DataFrame(students_list2, columns = ['name','grade',])

In [ ]:
students.merge(students1 , how='left', on='name')

In [ ]:
df = pd.DataFrame([[1, 2],[3,4] ] ,columns=['A','B'])
df1 = pd.DataFrame([[1,2],[3,4]],columns=['A','C'])

pd.concat([df,df1], axis= 1)

In [ ]:
#Reading data 
Housing_df = pd.read_csv('sample_data/california_housing_test.csv', delimiter = ',')
Housing_df.head()

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0

[5 rows x 9 columns]

In [ ]:
Housing_df.describe()

longitude    latitude  ...  median_income  median_house_value
count  3000.000000  3000.00000  ...    3000.000000          3000.00000
mean   -119.589200    35.63539  ...       3.807272        205846.27500
std       1.994936     2.12967  ...       1.854512        113119.68747
min    -124.180000    32.56000  ...       0.499900         22500.00000
25%    -121.810000    33.93000  ...       2.544000        121200.00000
50%    -118.485000    34.27000  ...       3.487150        177650.00000
75%    -118.020000    37.69000  ...       4.656475        263975.00000
max    -114.490000    41.92000  ...      15.000100        500001.00000

[8 rows x 9 columns]

In [ ]:
Housing_df.drop('longitude',axis =1,inplace=True)

In [ ]:
Housing_df.drop('latitude',axis =1,inplace=True)

In [ ]:
Housing_df.drop('housing_median_age',axis =1,inplace=True)

In [ ]:
Housing_df.head()

total_rooms  total_bedrooms  ...  median_income  median_house_value
0       3885.0           661.0  ...         6.6085            344700.0
1       1510.0           310.0  ...         3.5990            176500.0
2       3589.0           507.0  ...         5.7934            270500.0
3         67.0            15.0  ...         6.1359            330000.0
4       1241.0           244.0  ...         2.9375             81700.0

[5 rows x 6 columns]

In [ ]:
Housing_df.sum().sum()

632616966.8154

In [ ]:
Housing_df.sort_values(by='total_rooms', ascending=False)

total_rooms  total_bedrooms  ...  median_income  median_house_value
2429      30450.0          5033.0  ...         4.5936            174300.0
978       27870.0          5027.0  ...         4.8811            212200.0
292       24121.0          4522.0  ...         3.3799            239300.0
1146      23915.0          4135.0  ...         4.6357            244900.0
1597      21988.0          4055.0  ...         3.9963            191100.0
...           ...             ...  ...            ...                 ...
2690         21.0             7.0  ...         2.3750            175000.0
641          19.0            19.0  ...         0.5360            162500.0
2640         18.0             3.0  ...         0.5360            275000.0
740          16.0             4.0  ...         1.1250             60000.0
1115          6.0             2.0  ...         1.6250             55000.0

[3000 rows x 6 columns]

# Numpy



### NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### Installing Numpy 


#### C:\Users\Your Name>pip install numpy

In [66]:
import numpy as np

### Creating Arrays

In [4]:
#Why Numpy Arrays?
# Numpy arrays are a type of data structures that hold some benefits over 
# Python lists such as being more compact, faster access in reading 
# and writing items.
my_list = [0, 1, 2, 3, 4]
npy_my_list = np.array(my_list)

print(npy_my_list)

[0 1 2 3 4]


In [5]:
rand_arr = np.random.rand(3)

print(rand_arr)

[0.76772272 0.75442699 0.1553445 ]


In [6]:
#5 * 5 matrix
five_matrix = np.arange(1,26).reshape(5,5)

print(five_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


#### np. arange() is a Numpy method that returns the ndarray object containing evenly spaced values within the given range.

## Atributes & Functions

In [11]:
arr_atr = np.random.rand(5)

print(arr_atr)

[0.83478024 0.50040749 0.45436037 0.6984979  0.63419308]


In [12]:
# max value

arr_atr.max()

0.83478023974087

In [13]:
#min value
arr_atr.min()

0.4543603660427866

In [14]:
# indice of max val

arr_atr.argmax()

0

In [15]:
# indice of min val

arr_atr.argmin()

2

## Operations

In [16]:
a = np.arange(0,5)
print(a)

[0 1 2 3 4]


In [18]:
addition_arr = a + a
print(addition_arr)

[0 2 4 6 8]


In [19]:
subtration_arr = a - a
print(subtration_arr)

[0 0 0 0 0]


#### Find more on Numpy at : 
* https://www.w3schools.com/python/numpy/numpy_getting_started.asp

* https://cs231n.github.io/python-numpy-tutorial/
* https://www.tutorialspoint.com/numpy/index.html/


# Data Cleaning

## Titanic dataset

In [4]:
tcdf = pd.read_csv(r'C:\Users\home\KodingKahawa\Data-analysis-with-python\titanic.csv')

In [5]:
tcdf.head(5)

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0   7.2500  
1  female  38.0                        1                        0  71.2833  
2  female  26.0                        0                        0   7.9250  
3  female  35.0                        1                        0  53.1000  
4    male  35.0                        0                        0   8.0500

In [28]:
tcdf.count()

Survived                   887
Pclass                     887
Name                       887
Sex                        887
Age                        887
Siblings/Spouses Aboard    887
Parents/Children Aboard    887
Fare                       887
dtype: int64

### Missing values

In [30]:
num_rows = tcdf.shape[0]
num_rows

887

In [31]:
num_missing = num_rows - tcdf.count() 
num_missing

Survived                   0
Pclass                     0
Name                       0
Sex                        0
Age                        0
Siblings/Spouses Aboard    0
Parents/Children Aboard    0
Fare                       0
dtype: int64

In [8]:
# number of missing values in the data set
tcdf.isnull().sum().sum()

0

In [35]:
tcdf.isnull().values.any()

False

In [38]:
tcdf['Fare'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
882    False
883    False
884    False
885    False
886    False
Name: Fare, Length: 887, dtype: bool

## bike

In [12]:
bike = pd.read_csv(r'C:\Users\home\KodingKahawa\Data-analysis-with-python\bikedata.csv')

bike.head()

the_geom STREETNAME TYPE  \
0  LINESTRING (-122.3916341355079 37.774327550785...        4TH   ST   
1  LINESTRING (-122.39143433539678 37.77346692156...        4TH   ST   
2  LINESTRING (-122.39137353233207 37.77283099521...        4TH   ST   
3  LINESTRING (-122.39128424800653 37.77189717672...        4TH   ST   
4  LINESTRING (-122.39119934815182 37.77100919184...        4TH   ST   

        CNN           FROM_ST             TO_ST  FACILITY_T  YEAR_INSTA  \
0  19981000        CHANNEL ST    LONG BRIDGE ST  BIKE ROUTE        2011   
1  19982000    LONG BRIDGE ST   MISSION ROCK ST   BIKE LANE        2011   
2  19983000   MISSION ROCK ST    CHINA BASIN ST   BIKE LANE        2011   
3  19984000    CHINA BASIN ST  MISSION BAY BLVD   BIKE LANE        2011   
4  19985000  MISSION BAY BLVD  MISSION BAY BLVD   BIKE LANE        2011   

  DIRECT  SHAPE_LENG  ... NUMBER_ SHARROW UPDATE_YR SM_SWEEPER CONTRAFLOW  \
0     2W  319.214557  ...      19       1         0          0          0   
1     2W  232.220132  ...      19       0         0          0          0   
2     2W  341.000845  ...      19       0         0          0          0   
3     2W  324.263783  ...      19       0         0          0          0   
4     2W  165.499932  ...      19       0         0          0          0   

   CREATED_US                    CREATED_DA  LAST_EDITE  \
0         NaN  11/30/1899 12:00:00 AM +0000     JENWONG   
1         NaN  11/30/1899 12:00:00 AM +0000     JENWONG   
2         NaN  11/30/1899 12:00:00 AM +0000     JENWONG   
3         NaN  11/30/1899 12:00:00 AM +0000     JENWONG   
4         NaN  11/30/1899 12:00:00 AM +0000     JENWONG   

                     LAST_EDI_1   SHAPE_LEN  
0  02/22/2016 12:00:00 AM +0000  319.214557  
1  02/22/2016 12:00:00 AM +0000  232.220132  
2  02/22/2016 12:00:00 AM +0000  341.000845  
3  02/22/2016 12:00:00 AM +0000  324.263783  
4  02/22/2016 12:00:00 AM +0000  165.499932  

[5 rows x 30 columns]

In [42]:
bike.shape  # check out the dimension of the dataset


(5058, 30)

In [43]:
bike.dtypes  # look at the data types for each column

the_geom       object
STREETNAME     object
TYPE           object
CNN             int64
FROM_ST        object
TO_ST          object
FACILITY_T     object
YEAR_INSTA      int64
DIRECT         object
SHAPE_LENG    float64
SURFACE_TR     object
BARRIER        object
INNOVATIVE     object
NOTES          object
DIR            object
DOUBLE          int64
FY              int64
QTR             int64
STREET_        object
LENGTH        float64
NUMBER_        object
SHARROW         int64
UPDATE_YR       int64
SM_SWEEPER      int64
CONTRAFLOW      int64
CREATED_US     object
CREATED_DA     object
LAST_EDITE     object
LAST_EDI_1     object
SHAPE_LEN     float64
dtype: object

In [46]:
bike.columns.values  # return an array of column names


array(['the_geom', 'STREETNAME', 'TYPE', 'CNN', 'FROM_ST', 'TO_ST',
       'FACILITY_T', 'YEAR_INSTA', 'DIRECT', 'SHAPE_LENG', 'SURFACE_TR',
       'BARRIER', 'INNOVATIVE', 'NOTES', 'DIR', 'DOUBLE', 'FY', 'QTR',
       'STREET_', 'LENGTH', 'NUMBER_', 'SHARROW', 'UPDATE_YR',
       'SM_SWEEPER', 'CONTRAFLOW', 'CREATED_US', 'CREATED_DA',
       'LAST_EDITE', 'LAST_EDI_1', 'SHAPE_LEN'], dtype=object)

In [47]:
bike.columns.values.tolist()

['the_geom',
 'STREETNAME',
 'TYPE',
 'CNN',
 'FROM_ST',
 'TO_ST',
 'FACILITY_T',
 'YEAR_INSTA',
 'DIRECT',
 'SHAPE_LENG',
 'SURFACE_TR',
 'BARRIER',
 'INNOVATIVE',
 'NOTES',
 'DIR',
 'DOUBLE',
 'FY',
 'QTR',
 'STREET_',
 'LENGTH',
 'NUMBER_',
 'SHARROW',
 'UPDATE_YR',
 'SM_SWEEPER',
 'CONTRAFLOW',
 'CREATED_US',
 'CREATED_DA',
 'LAST_EDITE',
 'LAST_EDI_1',
 'SHAPE_LEN']

In [49]:
bike.isnull()  # checking missing values


the_geom  STREETNAME   TYPE    CNN  FROM_ST  TO_ST  FACILITY_T  \
0        False       False  False  False    False  False       False   
1        False       False  False  False    False  False       False   
2        False       False  False  False    False  False       False   
3        False       False  False  False    False  False       False   
4        False       False  False  False    False  False       False   
...        ...         ...    ...    ...      ...    ...         ...   
5053     False       False  False  False    False  False       False   
5054     False       False  False  False    False  False       False   
5055     False       False  False  False    False  False       False   
5056     False       False  False  False    False  False       False   
5057     False       False  False  False    False  False       False   

      YEAR_INSTA  DIRECT  SHAPE_LENG  ...  NUMBER_  SHARROW  UPDATE_YR  \
0          False   False       False  ...    False    False      False   
1          False   False       False  ...    False    False      False   
2          False   False       False  ...    False    False      False   
3          False   False       False  ...    False    False      False   
4          False   False       False  ...    False    False      False   
...          ...     ...         ...  ...      ...      ...        ...   
5053       False   False       False  ...     True    False      False   
5054       False   False       False  ...     True    False      False   
5055       False   False       False  ...     True    False      False   
5056       False   False       False  ...     True    False      False   
5057       False   False       False  ...    False    False      False   

      SM_SWEEPER  CONTRAFLOW  CREATED_US  CREATED_DA  LAST_EDITE  LAST_EDI_1  \
0          False       False        True       False       False       False   
1          False       False        True       False       False       False   
2          False       False        True       False       False       False   
3          False       False        True       False       False       False   
4          False       False        True       False       False       False   
...          ...         ...         ...         ...         ...         ...   
5053       False       False       False       False       False       False   
5054       False       False       False       False       False       False   
5055       False       False       False       False       False       False   
5056       False       False       False       False       False       False   
5057       False       False        True       False       False       False   

      SHAPE_LEN  
0         False  
1         False  
2         False  
3         False  
4         False  
...         ...  
5053      False  
5054      False  
5055      False  
5056      False  
5057      False  

[5058 rows x 30 columns]

In [50]:
bike.notnull()  # checking non-missing values


the_geom  STREETNAME  TYPE   CNN  FROM_ST  TO_ST  FACILITY_T  \
0         True        True  True  True     True   True        True   
1         True        True  True  True     True   True        True   
2         True        True  True  True     True   True        True   
3         True        True  True  True     True   True        True   
4         True        True  True  True     True   True        True   
...        ...         ...   ...   ...      ...    ...         ...   
5053      True        True  True  True     True   True        True   
5054      True        True  True  True     True   True        True   
5055      True        True  True  True     True   True        True   
5056      True        True  True  True     True   True        True   
5057      True        True  True  True     True   True        True   

      YEAR_INSTA  DIRECT  SHAPE_LENG  ...  NUMBER_  SHARROW  UPDATE_YR  \
0           True    True        True  ...     True     True       True   
1           True    True        True  ...     True     True       True   
2           True    True        True  ...     True     True       True   
3           True    True        True  ...     True     True       True   
4           True    True        True  ...     True     True       True   
...          ...     ...         ...  ...      ...      ...        ...   
5053        True    True        True  ...    False     True       True   
5054        True    True        True  ...    False     True       True   
5055        True    True        True  ...    False     True       True   
5056        True    True        True  ...    False     True       True   
5057        True    True        True  ...     True     True       True   

      SM_SWEEPER  CONTRAFLOW  CREATED_US  CREATED_DA  LAST_EDITE  LAST_EDI_1  \
0           True        True       False        True        True        True   
1           True        True       False        True        True        True   
2           True        True       False        True        True        True   
3           True        True       False        True        True        True   
4           True        True       False        True        True        True   
...          ...         ...         ...         ...         ...         ...   
5053        True        True        True        True        True        True   
5054        True        True        True        True        True        True   
5055        True        True        True        True        True        True   
5056        True        True        True        True        True        True   
5057        True        True       False        True        True        True   

      SHAPE_LEN  
0          True  
1          True  
2          True  
3          True  
4          True  
...         ...  
5053       True  
5054       True  
5055       True  
5056       True  
5057       True  

[5058 rows x 30 columns]

In [51]:
bike.isnull().values.any()  # only want to know if there are any missing values


True

In [52]:
bike.notnull().sum()  # knowling number of non-missing values for each variable


the_geom      5058
STREETNAME    4974
TYPE          4883
CNN           5058
FROM_ST       4918
TO_ST         4916
FACILITY_T    5058
YEAR_INSTA    5058
DIRECT        5058
SHAPE_LENG    5058
SURFACE_TR     157
BARRIER         97
INNOVATIVE     390
NOTES          339
DIR            526
DOUBLE        5058
FY            5058
QTR           5058
STREET_       4964
LENGTH        5058
NUMBER_       4967
SHARROW       5058
UPDATE_YR     5058
SM_SWEEPER    5058
CONTRAFLOW    5058
CREATED_US      77
CREATED_DA    5058
LAST_EDITE    5058
LAST_EDI_1    5058
SHAPE_LEN     5058
dtype: int64

In [13]:
bike.isnull().sum() # knowling number of non-missing values for each variable

the_geom         0
STREETNAME      84
TYPE           175
CNN              0
FROM_ST        140
TO_ST          142
FACILITY_T       0
YEAR_INSTA       0
DIRECT           0
SHAPE_LENG       0
SURFACE_TR    4901
BARRIER       4961
INNOVATIVE    4668
NOTES         4719
DIR           4532
DOUBLE           0
FY               0
QTR              0
STREET_         94
LENGTH           0
NUMBER_         91
SHARROW          0
UPDATE_YR        0
SM_SWEEPER       0
CONTRAFLOW       0
CREATED_US    4981
CREATED_DA       0
LAST_EDITE       0
LAST_EDI_1       0
SHAPE_LEN        0
dtype: int64

In [53]:
bike.isnull().sum().sum()  # knowing how many missing values in the data


29488

In [57]:
bike['CNN'].head(20)

0     19981000
1     19982000
2     19983000
3     19984000
4     19985000
5     19986000
6     19987000
7     19988000
8     19989000
9      5694000
10     5695000
11     5696000
12     5697000
13     5698000
14     2607000
15      508000
16      362000
17     3479000
18     3480000
19     4845000
Name: CNN, dtype: int64

In [14]:
bike["CNN"].isnull().values.any()  # only want to know if there are any missing values in CNN

True

In [58]:

bike["TO_ST"].isnull().values.any()


True

In [59]:

bike["TO_ST"].isnull().sum()

142

### Working on missing data

#### Fillna methods

In [16]:
Fill_no = bike.fillna(1000000)  # fill in missing with 1000000 and save the data to Fill_no
Fill_no.isnull().values.any()

False

In [18]:

Fill_str=bike["TO_ST"].fillna("missing")  # fill in missing with a string: "missing" and save the data to Fill_str
Fill_str.isnull().sum()

0

In [19]:

bike["SHAPE_LEN"].fillna(bike["SHAPE_LEN"].mean(), inplace=True)  # fill missing values with the sample mean and save the changes to the original data

In [20]:
bike["SHAPE_LEN"].isnull().values.any()

False

#### Other methods

In [71]:
bike.drop_duplicates(inplace=True)  # remove duplicates, if any, and save the changes to the original data


In [72]:
subset1 = bike.drop(bike.index[[1,7,9]])  # drop the 2nd, 8th, and 10th rows


In [73]:
subset2 = bike.drop(bike.index[range(1,11)])  # drop all rows between 2nd to 10th rows


In [74]:
subset3 = bike.drop(["LAST_EDITE", "LAST_EDI_1"], axis=1)  # drop LAST_EDITE and LAST_EDI_1